### ISSUE TITLE
Several Bugs

### ISSUE THREAD

**Issue by sineld** [Daynnnnn/statamic-database#7]
Hi @Daynnnnn 

Since this repo has not been updates about a year, there are several issues with Statamic.

EntryQueryBuilder is not compatible:

it's now:
`public function paginate($perPage = null, $columns = ['*'])`
has to be:
`public function paginate($perPage = null, $columns = [], $pageName = 'page', $page = null)`

Also after adding a sample blog post it is listed in collection but when we edit it, field contents disappear.

Do you plan to update?

Thanks.

**Comment by Daynnnnn** [comment]
Hey! There's been a PR open since just after I released this package to make statamics official eloquent driver support all content. https://github.com/statamic/eloquent-driver/pull/42

After this PR is merged, I'll create a migration command/guide to migrate to the official package, than abandon this one.

That said, I appreciate people are still using this, so I'll try get a fix out over the weekend. Thanks for raising :)

**Comment by sineld** [comment]
Thank you for your urgent reply and good news.
I'm looking forward to hearing from your updates.
Cheers!

**Comment by Daynnnnn** [comment]
These should be sorted in v1.6.0, let me know if you're still having issues!
